CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fullname" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "movies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text,
  "duration_minutes" integer NOT NULL,
  "release_date" date,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "cinemas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "city" varchar NOT NULL,
  "address" text,
  "created_at" timestamp
);

CREATE TABLE "studios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cinema_id" integer NOT NULL,
  "name" varchar NOT NULL,
  "total_seats" integer NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "seats" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "studio_id" integer NOT NULL,
  "row_code" char(1) NOT NULL,
  "seat_number" integer NOT NULL
);

CREATE TABLE "schedules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "movie_id" integer NOT NULL,
  "studio_id" integer NOT NULL,
  "start_time" timestamp NOT NULL,
  "end_time" timestamp NOT NULL,
  "price" decimal(10,2) NOT NULL,
  "status" varchar DEFAULT 'SHOWING',
  "created_at" timestamp
);

CREATE TABLE "transactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "schedule_id" integer,
  "total_amount" decimal(10,2) NOT NULL,
  "payment_method" varchar,
  "payment_time" timestamp,
  "status" varchar DEFAULT 'PENDING',
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "tickets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_id" integer NOT NULL,
  "schedule_id" integer NOT NULL,
  "seat_id" integer NOT NULL,
  "price" decimal(10,2),
  "created_at" timestamp
);

COMMENT ON COLUMN "cinemas"."name" IS 'Cabang Bioskop, misal: MKP XXI';
COMMENT ON COLUMN "studios"."name" IS 'Nama Studio, misal: Studio 1, IMAX';
COMMENT ON COLUMN "seats"."row_code" IS 'Baris A, B, C';
COMMENT ON COLUMN "seats"."seat_number" IS 'Nomor 1, 2, 3';
COMMENT ON COLUMN "schedules"."status" IS 'SHOWING, CANCELLED, ENDED';
COMMENT ON COLUMN "transactions"."status" IS 'PENDING, PAID, CANCELLED, REFUNDED';
COMMENT ON COLUMN "tickets"."price" IS 'Harga saat beli';

ALTER TABLE "studios" ADD FOREIGN KEY ("cinema_id") REFERENCES "cinemas" ("id");
ALTER TABLE "seats" ADD FOREIGN KEY ("studio_id") REFERENCES "studios" ("id");
ALTER TABLE "schedules" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id");
ALTER TABLE "schedules" ADD FOREIGN KEY ("studio_id") REFERENCES "studios" ("id");
ALTER TABLE "transactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "transactions" ADD FOREIGN KEY ("schedule_id") REFERENCES "schedules" ("id");
ALTER TABLE "tickets" ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id");
ALTER TABLE "tickets" ADD FOREIGN KEY ("schedule_id") REFERENCES "schedules" ("id");
ALTER TABLE "tickets" ADD FOREIGN KEY ("seat_id") REFERENCES "seats" ("id");
